### ISSUE TITLE
headerRight 내에서 visable 이라는 변수에 따라 <Pressable>을 보이고 숨기기 어떻게 하는지 모르겠다.! 

### ISSUE THREAD

**Issue by hycv** [Care-Giver/CareGiver#65]
screen 내에서 visable 변수의 true, false 여부에 따라 Pressable 을 보이거나 없애고 싶은데 이를 코드를 어떻게 짤지 감이 안옵니다. 그리고 구글링도 꽤 해봤는데 어떻게 찾아야 할지도 점점 모르겠어서.. ㅎㅎ.. ㅜ 
@smnchoi @minSsan 

해당 커밋 링크 : 
ecc09cb10c7a2e78fb0cdd7d43e87c4e50d1f386 

코드 : 
```typescript
export const MyProfileManagementScreen: FC<
  StackScreenProps<NavigatorParamList, "my-profile-management-screen">
> = observer(({ navigation, route }) => {
  const [visiable, setVisable] = useState(true)

  useLayoutEffect(() => {
    navigation.setOptions({
  
//! visiable 변수에 상관없이 그냥 그 위치에 그대로 항상 있는 headerRight 버튼 코드
      headerRight: () => (
        <Pressable
          onPress={() => setVisable((prev) => !prev)}
          style={{
            marginLeft: "auto",
            marginRight: 8, //!
          }}
        >
          <Image style={{ width: 28, height: 28 }} source={images.pencil} />
        </Pressable>
      ),

      //?! 위의 코드를 아래처럼 visable 여부에 따라 able, disable 하고 싶은데 문법상 틀린거같은데 어떻게 고쳐야 할지를 모르겠는.. 
      /*headerRight: () => (
        {visiable?  (<Pressable
          onPress={() => setVisable((prev) => !prev)}
          style={{
            marginLeft: "auto",
            marginRight: 8, //!
          }}
        >
          <Image style={{ width: 28, height: 28 }} source={images.pencil} />
        </Pressable>) : null }
       
      ),*/
    })
  }, [visiable])
```

**Comment by smnchoi** [comment]
피드백 남겼습니다! 
adbfbcefb7686c9f1026c991ef110a196019b937

**Comment by smnchoi** [comment]
@hycv  @minSsan 

# 커스텀 헤더 컴포넌트와 스크린 사이에서 값을 주고 받기 위해선 어떻게 해야 할까요?
여러가지 방법이 있겠지만, react navigation 을 사용하고 있는 저희 프로젝트에서는
params 를 통해서 값을 주고 받는 것이 가장 편리합니다.

params 는 모든 Screen 컴포넌트에 자동으로 부여되는 요소입니다.

``` useRoute().route.params ``` 를 통해 params 값을 읽을수 있으며,

``` useNavigation().navigation.setParams({ param이름: 값 }) ``` 을 통해 params 값을 변경할 수 있습니다.

```params``` 와 ```setParams```, 꼭 기억해주시길 바랍니다!
더 자세한 정보는 아래 react navigation 공식 문서를 참고해주세요 :) 

https://reactnavigation.org/docs/navigation-prop/#setparams

# 추가 Tip:
원래 params 는 서로 다른 screen 사이에서 data 를 전달할때 쓰이기 위해 만들어진 개념입니다.
A screen 에서 B screen 으로 이동시, A screen 에서의 값들을 B screen 으로 전달하기 위해서이죠.
이는 마치, React 와 같은 웹 개발에서 Router 를 사용해서 URL parameters 방식으로 페이지들끼리 데이터를 전달하는 개념과 유사합니다.

![image](https://user-images.githubusercontent.com/70505699/219002300-ae0fb49c-0513-42fa-b0d0-2378e08dc287.png)

앱 개발의 역사는 웹을 기반으로 발전하였으며, 특히 React Native 는 React 를 기반으로 만들어졌으니,
특히 더 유사합니다.

하지만, 이 params 를 통해 screen 사이 데이터를 주고받는 방법은 screen 이 많아지면 많아질수록, (A -> B -> C -> ... )
이전의 screen 들의 데이터를 계속해서 넘기고 넘겨야 하니, 지루한 코드의 반복으로 이어지는 문제가 발생합니다.
global state management 는 바로 이러한 문제를 해결하고, data flow 를 보다 더 잘 관리하기 위해 추가된 개념입니다.

redux, recoil, MST 등등이 있으며, 저희 앱에서는 MST 를 사용하지요.

즉, 저희 앱과 같이 global state management 를 사용하는 경우에는 왠만하면 params 를 통해 screen 사이 data 를 주고받는것을
지양해야 합니다. params 대신에, MST 를 사용하여 주고 받아야 하지요. 따라서, 대부분의 경우에서 params 를 사용할 일이 없습니다.

### 하지만, 
지금의 사례처럼 **하나의** 스크린에서 이루어지는 data 교환은 params 를 사용해서 구현하면
훨씬 쉽고 간단합니다

경우에 맞게 잘 활용하시길 바랍니다 :)

**Comment by hycv** [comment]
@smnchoi 
자세한 피드백과 자세한 답변 감사합니다!! 많은 도움이 되었습니다 !! ㅜㅜ 특히 Params 에 대한 추가글은 진짜 테크 블로그 읽는것 같았습니다 🥹

한가지 질문이 있는데요, params 에 대해 찾다가 아래와 같은 문서를 읽었습니다. 
[https://reactnavigation.org/docs/params/](url)
위의 문서를 읽고 제가 이해한 바는, navigation.navigate('RouteName', { paramName: 'value' }) 와 같은 코드를 통해 params를 만들고 전달한다. 그리고 route.params 를 통해 이를 읽는다, setParams 를 통해 수정한다 였습니다. 
그런데 피드백 해주신 코드 와 작성해주신 글을 통해 navigation.navigate 의 단계를 거치지 않아도 기본적으로 스크린에 주어진 Params를 사용하고 이를 수정해 위의 코드처럼 visiable 과 같은 필요한 params 를 만들고 사용할 수 있다는 것을 알게되었습니다. 
그렇다면, navigation.navigate 의 존재 목적과 활용할 때 등이 궁금합니다. (피드백 해주신 제 코드에서는 사용하지 않고도 작동이 잘 되었기에..!)
감사합니다 !

**Comment by hycv** [comment]
다시 제가 첨부한 문서를 읽어보니 navigation.navigate 를 사용한것은 다른 페이지로 이동할 때 params 를 넘겨주는걸 보여주려고 사용한것 같다는 생각이 들었습니다. 그렇다면, 저의 코드와 같은 헤더 컴포넌트와 스크린 간의 단순한 data 주고 받을때에는 setParams 를 사용하면 되는것이고.
다른 스크린으로 이동하면서 params 를 넘겨줘야 할때는 navigation.navigate(~) 안에서 params 를 만들고 전달한다. 라고 이해하면 되는 것일까요?

**Comment by smnchoi** [comment]
질문 이해했습니다 :) 
좋은 질문이네요!

제가 끝내야할 일이 있어서 1시간뒤에 답변드리겠습니다!

**Comment by hycv** [comment]
넵 천천히 주셔도 괜찮습니다!! 감사합니다 ㅎㅎ

**Comment by smnchoi** [comment]
맞습니다!

navigation.navigate 함수는 함수 이름에서도 유추 할 수 있듯이,
navigate 즉, **다른 스크린으로의 이동** 에 쓰이는 함수입니다!
이때, 추가적으로 ```params``` 를 사용하여 데이터 역시 전달해줄 수 있습니다!

이 세상에 있는 대부분의 앱은 스크린이 2개 이상일테고,
그렇다면, 대부분 다 스크린 이동이 필수적이겠지요?
따라서, navigate 함수는 매우 빈번하게 쓰입니다.

이때, 데이터를 전달해야하는 경우도 많기에, params 역시 매우 많이 쓰입니다!
```navigate("이동할 스크린이름", {"넘길데이터 키": "넘길데이터 밸류", ...})```
형식으로 사용됩니다!

우리 앱에서는 global state management 를 사용하므로,
예외적으로 params 를 많이 사용하지 않고 있었다는 점 기억해주시길 바랍니다.

유튜버 Vadim 이나, 노마드코더 Nico 의 다른 강의들을 보시다보면 아시겠지만,
기타 다른 앱들 클론 코딩하다보면, params 로 데이터를 넘기는일이 매우 빈번하게 일어납니다 :) 

저희 앱에서도 특정한 경우에는 사용될 수 있습니다.
A -> B 이렇게 겨우 한스크린만 이동하여 데이터를 전달하는 경우에는
굳이 global state 를 사용하지않고, params 를 통해 전달하는 것이 더 효과적일테니 말입니다 ☺️

**Comment by hycv** [comment]
헷갈리던 부분이 완전히 이해 됐습니다! 너무나 정성스러운 답변 감사합니다!! 🥹 다음에 시간 내어 navigation 기능들에 대해 더 공부해보도록 하겠습니다!
